baseURL = "/"
languageCode = "en-us"
title = "Charisma"
theme = "lithium_charismaUi"
googleAnalytics = ""
disqusShortname = ""


[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "1"
    url = "/episode-1"
    identifier = "episode-1"
    weight = -50
[[menu.main]]
    name = "2"
    url = "episode-2"
    identifier = "episode-2"
    weight = -49

[[menu.sub]]
    name = "EN"
    url = "#"
    identifier = "en-link"
[[menu.sub]]
    name = "DE"
    url = "#"
    identifier = "de-link"
[[menu.sub]]
    name = "¢"
    url = "/credits"
    identifier = "credits-link"

[params]
    description = "Independent web series, a sitcom produced by artists Sarah M. Harrison and Wojciech Kosma."

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

