baseURL = "/"
languageCode = "en-us"
title = "Charisma, 2017"
theme = "lithium_charismaUi"
googleAnalytics = ""
disqusShortname = ""


[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"


[[menu.ctrl]]
    name = "grid-activate"
    url = "/"
    identifier = "grid-activate-link"
    post = ""
    weight = "-10"

[[menu.main]]
    name = "DE"
    url = "#"
    identifier = "de-link"
[[menu.main]]
    name = "EN"
    url = "#"
    identifier = "en-link"
[[menu.main]]
    name = "¢"
    url = "credits"
    identifier = "credits-link"

[params]
    description = "Independent web series, a sitcom produced by artists Sarah M. Harrison and Wojciech Kosma."

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

