baseURL = "/"
languageCode = "en-us"
title = "Charisma"
theme = "lithium_charismaUi"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "One"
    url = "/episode-1"
    identifier = "episode-1"
    weight = -50
[[menu.main]]
    name = "Two"
    url = "/episode-2"
    identifier = "episode-2"
    weight = -49
[[menu.main]]
    name = "Three"
    url = "/episode-3"
    identifier = "episode-3"
    weight = -48
[[menu.main]]
    name = "Four"
    url = "/episode-4"
    identifier = "episode-4"
    weight = -47
[[menu.main]]
    name = "Five"
    url = "/episode-5"
    identifier = "episode-5"
    weight = -46
[[menu.main]]
    name = "Six"
    url = "/episode-6"
    identifier = "episode-6"
    weight = -45

[[menu.sub]]
    name = "EN"
    url = "#en"
    identifier = "en-link"
    weight = -50
    post = "en-GB"
[[menu.sub]]
    name = "DE"
    url = "#de"
    identifier = "de-link"
    weight = -49
    post = "de-DE"

[params]
    description = "Independent web series, a sitcom produced by artists Sarah M. Harrison and Wojciech Kosma."

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

