baseURL = "/"
languageCode = "en-us"
title = "Charisma, 2017"
theme = "lithium_charismaUi"
googleAnalytics = ""
disqusShortname = ""


[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"


[[menu.ctrl]]
    name = "grid-activate"
    url = "/"
    identifier = "grid-activate-link"
    post = ""
    weight = "-10"
[[menu.ctrl]]
    name = "bg-toggle"
    url = "/"
    identifier = "bg-toggle-link"
    post = "bg toggle"
    weight = "-9"
[[menu.ctrl]]
    name = "zone-segment-toggle"
    url = "/"
    identifier = "zone-segmentbg-toggle-link"
    post = "placement zones"
    weight = "-8"
[[menu.ctrl]]
    name = "zone-bg-toggle"
    url = "/"
    identifier = "zone-bg-toggle-link"
    post = "zone bg"
    weight = "-7"

[[menu.main]]
    name = "DE"
    url = "#"
    identifier = "de-link"
[[menu.main]]
    name = "EN"
    url = "#"
    identifier = "en-link"
[[menu.main]]
    name = "¢"
    url = "credits"
    identifier = "credits-link"






[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

